# Generated by Django 3.0.6 on 2020-07-11 11:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carsforsale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('car_picture', models.ImageField(blank=True, default='noimage.jpg', upload_to='cars_pictures')),
                ('price', models.CharField(default=0, max_length=10)),
                ('status', models.CharField(choices=[('available', 'available'), ('sold', 'sold')], default='avalable', max_length=10)),
                ('make', models.CharField(default='', max_length=50)),
                ('model', models.CharField(default='', max_length=50)),
                ('manufactured', models.CharField(default='', max_length=4)),
                ('mileage', models.CharField(default=0, max_length=10)),
                ('transmission', models.CharField(choices=[('Automatic', 'Automatic'), ('Manual', 'Manual')], default='', max_length=20)),
                ('fuel_type', models.CharField(choices=[('Diesel', 'Diesel'), ('Petrol', 'Petrol')], default='', max_length=10)),
                ('color', models.CharField(default='', max_length=50)),
                ('car_description', models.TextField()),
                ('city', models.CharField(max_length=50)),
                ('province', models.CharField(choices=[('Gauteng', 'Gauteng'), ('North West', 'North west'), ('Free State', 'Free State'), ('Western Cape', 'Western Cape'), ('Mpumalanga', 'Mpumalanga'), ('Limpopo', 'Limpopo'), ('Eastern Cape', 'Eastern Cape'), ('Northern Cape', 'Northern Cape'), ('KwaZulu Natal', 'KwaZulu Natal')], max_length=50)),
                ('phone', models.CharField(default=0, max_length=10)),
                ('email', models.EmailField(default='example@gmail.com', max_length=50)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Carsforsale',
            },
        ),
    ]
