# Generated by Django 3.0.6 on 2020-07-11 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsforsale', '0002_auto_20200711_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carsforsale',
            name='email',
            field=models.EmailField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='carsforsale',
            name='mileage',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='carsforsale',
            name='price',
            field=models.CharField(default='', max_length=10),
        ),
    ]
