# Generated by Django 3.0.6 on 2020-06-01 13:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('carsforsale', '0002_auto_20200601_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='carsforsale',
            name='city',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carsforsale',
            name='province',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
