# Generated by Django 3.0.6 on 2020-06-01 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsforsale', '0003_auto_20200601_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='carsforsale',
            name='mileage',
            field=models.IntegerField(default=0),
        ),
    ]
