# Generated by Django 3.0.6 on 2020-07-11 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carsforsale', '0004_carsforsale_delearship'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carsforsale',
            old_name='delearship',
            new_name='dealership',
        ),
    ]
