# Generated by Django 3.0.6 on 2020-06-02 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsforsale', '0004_carsforsale_mileage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carsforsale',
            name='make_and_model',
        ),
        migrations.AddField(
            model_name='carsforsale',
            name='make',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carsforsale',
            name='model',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='carsforsale',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='carsforsale',
            name='color',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='carsforsale',
            name='email',
            field=models.EmailField(default='example@gmail.com', max_length=50),
        ),
        migrations.AlterField(
            model_name='carsforsale',
            name='province',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='carsforsale',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='carsforsale',
            name='transmission',
            field=models.CharField(default='', max_length=20),
        ),
    ]
