# Generated by Django 3.0.6 on 2020-06-02 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsforsale', '0007_auto_20200602_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carsforsale',
            name='province',
            field=models.CharField(choices=[('Gauteng', 'Gauteng'), ('North West', 'North west'), ('Free State', 'Free State'), ('Western Cape', 'Western Cape'), ('Mpumalanga', 'Mpumalanga'), ('Limpopo', 'Limpopo'), ('Eastern Cape', 'Eastern Cape'), ('Northern Cape', 'Northern Cape'), ('KwaZulu Natal', 'KwaZulu Natal')], max_length=50),
        ),
    ]
