# Generated by Django 3.0.6 on 2020-06-03 11:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsforsale', '0008_auto_20200602_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('date_of_visit', models.DateField(default=datetime.datetime.now)),
                ('time_of_visit', models.TimeField(default=datetime.datetime.now)),
                ('assisted_by', models.CharField(max_length=20)),
                ('comments', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Visitors',
            },
        ),
    ]
