# Generated by Django 3.0.6 on 2020-06-04 09:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsforsale', '0009_visitor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Visitor',
        ),
        migrations.RemoveField(
            model_name='carsforsale',
            name='time_and_date',
        ),
        migrations.AddField(
            model_name='carsforsale',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='carsforsale',
            name='transmission',
            field=models.CharField(choices=[('Automatic', 'Automatic'), ('Manual', 'Manual')], default='', max_length=20),
        ),
    ]
