# Generated by Django 3.0.6 on 2020-06-04 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carsforsale', '0010_auto_20200604_0959'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='carsforsale',
            unique_together={('id', 'title')},
        ),
    ]
