# Generated by Django 3.0.6 on 2020-06-04 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carsforsale', '0011_auto_20200604_1734'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carsforsale',
            options={},
        ),
    ]
