# Generated by Django 3.0.6 on 2020-07-09 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carsforsale', '0013_auto_20200612_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='carsforsale',
            name='posted_by',
            field=models.ForeignKey(default=int, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
