# Generated by Django 3.0.6 on 2020-07-09 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsforsale', '0014_carsforsale_posted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carsforsale',
            name='car_picture',
            field=models.ImageField(blank=True, null=True, upload_to='cars_pictures'),
        ),
    ]
