# Generated by Django 3.0.6 on 2020-07-09 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsforsale', '0015_auto_20200709_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carsforsale',
            name='car_picture',
            field=models.ImageField(blank=True, default='noimage.jpg', upload_to='cars_pictures'),
        ),
    ]
