# Generated by Django 3.0.6 on 2020-07-09 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carsforsale', '0016_auto_20200709_1427'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carsforsale',
            old_name='posted_by',
            new_name='creator',
        ),
    ]
