# Generated by Django 3.0.6 on 2020-07-09 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsforsale', '0017_auto_20200709_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='carsforsale',
            name='status',
            field=models.CharField(default='avalable', max_length=15),
        ),
    ]
