# Generated by Django 3.0.6 on 2020-07-09 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsforsale', '0018_carsforsale_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carsforsale',
            name='status',
            field=models.CharField(choices=[('available', 'available'), ('sold', 'sold')], default='avalable', max_length=15),
        ),
    ]
