# Generated by Django 3.0.6 on 2020-07-09 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsforsale', '0019_auto_20200709_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carsforsale',
            name='status',
            field=models.CharField(choices=[('available', 'available'), ('sold', 'sold')], default='avalable', max_length=10),
        ),
    ]
